server:
  port: 9090

spring:
  jpa:
    #    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/hotelManagement?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  #    properties:
  #      hibernate:
  #        format_sql: true


  # swagger-ui custom path
  #springdoc:
  #  swagger-ui:
  #    path: /swagger-ui.html


logging:
  level:
    #    root: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type: TRACE
        com:
          vr:
            SplitEase: DEBUG